### ISSUE TITLE
BH_style_05: Landing Page - update styling

### ISSUE THREAD

**Issue by BethLambertMatthews** [troysnowden/burger_hunt#29]

**Comment by KirstyJHarris** [comment]
Add "play" to arrow on landing page
Centre arrow
Add line to footer 
Background colour updated

<img width="782" alt="Screenshot 2021-11-25 at 08 19 12" src="https://user-images.githubusercontent.com/87372132/143404906-fccd9e0e-74a2-40c5-a9ed-e150cbfbbcf8.png">
